module.exports.createUsersTableQuery = `
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name = 'Users' AND xtype = 'U')
BEGIN
    CREATE TABLE Users (
        UserId INT IDENTITY(1,1) PRIMARY KEY,
        Fname NVARCHAR(25),
        Lname NVARCHAR(25),
        DOB DATE,
        Email NVARCHAR(50),
        Password NVARCHAR(MAX),
        EntryTime DATETIME DEFAULT GETDATE()
    );
END;

-- Check and add columns if they do not exist
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'UserId')
BEGIN
    ALTER TABLE Users ADD UserId INT IDENTITY(1,1) PRIMARY KEY;
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Fname')
BEGIN
    ALTER TABLE Users ADD Fname NVARCHAR(25);
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Lname')
BEGIN
    ALTER TABLE Users ADD Lname NVARCHAR(25);
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'DOB')
BEGIN
    ALTER TABLE Users ADD DOB DATE;
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Email')
BEGIN
    ALTER TABLE Users ADD Email NVARCHAR(50);
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'Password')
BEGIN
    ALTER TABLE Users ADD Password NVARCHAR(MAX);
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'EntryTime')
BEGIN
    ALTER TABLE Users ADD EntryTime DATETIME DEFAULT GETDATE();
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Users' AND COLUMN_NAME = 'UUID')
BEGIN
    ALTER TABLE Users ADD UUID DATETIME DEFAULT GETDATE();
END;
`;
